CREATE TABLE empresas (
    id VARCHAR(255) NOT NULL,
    codigo VARCHAR(255) NOT NULL,
    razon_social VARCHAR(255) NOT NULL,
    cuit VARCHAR(255) NOT NULL,
    fecha_adhesion DATE NOT NULL,
    numero_cuenta VARCHAR(255) NOT NULL,
    saldo DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE empresas ADD CONSTRAINT UK_empresa_codigo UNIQUE (codigo);
ALTER TABLE empresas ADD CONSTRAINT UK_empresa_cuit UNIQUE (cuit);
ALTER TABLE empresas ADD CONSTRAINT UK_empresa_numero_cuenta UNIQUE (numero_cuenta);

CREATE TABLE transferencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cuenta_debito VARCHAR(255) NOT NULL,
    cuenta_credito VARCHAR(255) NOT NULL,
    importe DECIMAL(19, 2) NOT NULL,
    fecha DATE NOT NULL,
    empresa_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE transferencias ADD CONSTRAINT FK_transferencia_empresa
FOREIGN KEY (empresa_id) REFERENCES empresas(id);